site_name: Spacewalks
use_directory_urls: false
theme:
  name: "material"
  font: false
nav:
  - Spacewalks Documentation: index.md
  - Tutorials: tutorials.md
  - Refenences: reference.md
  - Nacground: explanation.md

plugins:
  - mkdocstrings



